apiVersion: v1
kind: Service
metadata:
  name: cs548-billing
  labels:
    app: cs548-billing
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
  - name: https
    port: 8181
  selector:
    app: cs548-billing
